
export const FIND_MANY_USERS_BY_DOCTOR_REQUEST = 'FIND_MANY_USERS_BY_DOCTOR_REQUEST';
export const FIND_MANY_USERS_BY_DOCTOR_SUCCESS = 'FIND_MANY_USERS_BY_DOCTOR_SUCCESS';
export const FIND_MANY_USERS_BY_DOCTOR_FAILURE = 'FIND_MANY_USERS_BY_DOCTOR_FAILURE';
