
export const GEN_TESTING_INPUT_REQUEST = 'GEN_TESTING_INPUT_REQUEST';
export const GEN_TESTING_INPUT_SUCCESS = 'GEN_TESTING_INPUT_SUCCESS';
export const GEN_TESTING_INPUT_FAILURE = 'GEN_TESTING_INPUT_FAILURE';
