
export const FIND_MANY_GEN_TESTINGS_REQUEST = 'FIND_MANY_GEN_TESTINGS_REQUEST';
export const FIND_MANY_GEN_TESTINGS_SUCCESS = 'FIND_MANY_GEN_TESTINGS_SUCCESS';
export const FIND_MANY_GEN_TESTINGS_FAILURE = 'FIND_MANY_GEN_TESTINGS_FAILURE';

export const DELETE_GEN_TESTINGS_REQUEST = 'DELETE_GEN_TESTINGS_REQUEST';
export const DELETE_GEN_TESTINGS_SUCCESS = 'DELETE_GEN_TESTINGS_SUCCESS';
export const DELETE_GEN_TESTINGS_FAILURE = 'DELETE_GEN_TESTINGS_FAILURE';
