
export const FIND_PATIENT_TESTING_RESULT_REQUEST = 'FIND_PATIENT_TESTING_RESULT_REQUEST';
export const FIND_PATIENT_TESTING_RESULT_SUCCESS = 'FIND_PATIENT_TESTING_RESULT_SUCCESS';
export const FIND_PATIENT_TESTING_RESULT_FAILURE = 'FIND_PATIENT_TESTING_RESULT_FAILURE';

export const SEND_MAIL_TO_PATIENT_REQUEST = 'SEND_MAIL_TO_PATIENT_REQUEST';
export const SEND_MAIL_TO_PATIENT_SUCCESS = 'SEND_MAIL_TO_PATIENT_SUCCESS';
export const SEND_MAIL_TO_PATIENT_FAILURE = 'SEND_MAIL_TO_PATIENT_FAILURE';
