
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const FIND_ONE_USER_REQUEST = 'FIND_ONE_USER_REQUEST';
export const FIND_ONE_USER_SUCCESS = 'FIND_ONE_USER_SUCCESS';
export const FIND_ONE_USER_FAILURE = 'FIND_ONE_USER_FAILURE';
