
export const SUB_GEN_TESTING_CREATE_REQUEST = 'SUB_GEN_TESTING_CREATE_REQUEST';
export const SUB_GEN_TESTING_CREATE_SUCCESS = 'SUB_GEN_TESTING_CREATE_SUCCESS';
export const SUB_GEN_TESTING_CREATE_FAILURE = 'SUB_GEN_TESTING_CREATE_FAILURE';
