
export const FIND_MANY_GEN_TESTING_REQUEST = 'FIND_MANY_GEN_TESTING_REQUEST';
export const FIND_MANY_GEN_TESTING_SUCCESS = 'FIND_MANY_GEN_TESTING_SUCCESS';
export const FIND_MANY_GEN_TESTING_FAILURE = 'FIND_MANY_GEN_TESTING_FAILURE';
