
export const UPDATE_PATIENT_REQUEST = 'UPDATE_PATIENT_REQUEST';
export const UPDATE_PATIENT_SUCCESS = 'UPDATE_PATIENT_SUCCESS';
export const UPDATE_PATIENT_FAILURE = 'UPDATE_PATIENT_FAILURE';

export const FIND_ONE_PATIENT_REQUEST = 'FIND_ONE_PATIENT_REQUEST';
export const FIND_ONE_PATIENT_SUCCESS = 'FIND_ONE_PATIENT_SUCCESS';
export const FIND_ONE_PATIENT_FAILURE = 'FIND_ONE_PATIENT_FAILURE';
