
export const CREATE_GEN_TESTING_REQUEST = 'CREATE_GEN_TESTING_REQUEST';
export const CREATE_GEN_TESTING_SUCCESS = 'CREATE_GEN_TESTING_SUCCESS';
export const CREATE_GEN_TESTING_FAILURE = 'CREATE_GEN_TESTING_FAILURE';
