
export const UPDATE_GEN_REQUEST = 'UPDATE_GEN_REQUEST';
export const UPDATE_GEN_SUCCESS = 'UPDATE_GEN_SUCCESS';
export const UPDATE_GEN_FAILURE = 'UPDATE_GEN_FAILURE';
export const FIND_ONE_GEN_REQUEST = 'FIND_ONE_GEN_REQUEST';
export const FIND_ONE_GEN_SUCCESS = 'FIND_ONE_GEN_SUCCESS';
export const FIND_ONE_GEN_FAILURE = 'FIND_ONE_GEN_FAILURE';
