
export const FIND_MY_TESTING_RESULT_REQUEST = 'FIND_MY_TESTING_RESULT_REQUEST';
export const FIND_MY_TESTING_RESULT_SUCCESS = 'FIND_MY_TESTING_RESULT_SUCCESS';
export const FIND_MY_TESTING_RESULT_FAILURE = 'FIND_MY_TESTING_RESULT_FAILURE';
